spring.application.name=demo


#spring.datasource.url=jdbc:postgresql://localhost:5432/Local
#spring.datasource.username=postgres
#spring.datasource.password=root

spring.datasource.url=jdbc:postgresql://database-1.cev4umwggj1n.us-east-1.rds.amazonaws.com:5432/Local
spring.datasource.username=postgres
spring.datasource.password=RdsDev#2026!PgSafe91

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.messages.encoding=UTF-8
spring.messages.basename=messages

#RdsDev#2026!PgSafe91

#spring.mvc.apiversion.use.query-parameter=version

#spring.mvc.apiversion.use.path-segment=0

#spring.mvc.apiversion.use.header=X-API-VERSION

#spring.mvc.apiversion.use.media-type-parameter[application/json]=version
